const tableTiles = [
    {
        id: 1,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 2,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 3,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 4,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 5,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 6,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 7,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 8,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 9,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 10,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 11,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 12,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 13,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 14,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 15,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 16,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 17,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 18,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 19,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 20,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 21,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 22,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 23,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 24,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 25,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 26,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 27,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 28,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 29,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 30,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 31,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 32,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 33,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 34,
        events: [],
        time: '',
        date: '',
        color: '',
    },
    {
        id: 35,
        events: [],
        time: '',
        date: '',
        color: '',
    },
];

export default tableTiles;
